---
- name: Restart Zcashd service
  become: true
  service:
    name: "{{ _service_name }}"
    state: restarted
  listen: Restart service
  ignore_errors: true

- name: Stop Zcashd systemd service
  become: true
  service:
    name: "{{ _service_name }}"
    state: stopped
    enabled: false
  listen: Uninstall service
  ignore_errors: true

- name: Remove Zcashd systemd service file
  become: true
  file:
    path: "/etc/systemd/system/{{ _service_name }}.service"
    state: absent
  listen: Uninstall service

- name: Remove Zcashd install dir
  become: true
  file:
    path: "{{ install_dir }}"
    state: absent
  listen: Uninstall service

- name: Remove Zcashd config
  become: true
  file:
    path: "{{ config_dir }}"
    state: absent
  listen: Uninstall service

- name: Remove Zcashd user
  become: true
  user:
    name: "{{ zcashd_user }}"
    state: absent
    remove: true
  listen: Uninstall service

- name: Remove Zcashd group
  become: true
  group:
    name: "{{ zcashd_user }}"
    state: absent
  listen: Uninstall service
