---
- name: Uninstall provisioned container components
  when: uninstall|bool == true
  block:
    - name: Broadcast uninstall signal
      command: /bin/true
      notify: Container uninstall
  always:
    - name: End play following uninstallation
      meta: end_play

- name: Create bridged Ethereum network for components to communicate
  community.docker.docker_network:
    name: ethereum

- name: Ensure existence of runtime dir
  become: true
  file:
    path: "{{ ops_runtime_dir }}"
    state: directory
    mode: 0777

- name: Generate Prysm beacon environment vars
  become: true
  template:
    src: ".env.j2"
    dest: "{{ beacon_env_file }}"
    owner: "root"
    group: "root"
    mode: 0644
    backup: true
  vars:
    conf: "{{ _default_beacon_config|combine(beacon_config) }}"
    env_conf: "{{ beacon_env_vars }}"
  register: "beacon_container_env"

- name: Generate Prysm validator environment vars
  become: true
  template:
    src: ".env.j2"
    dest: "{{ validator_env_file }}"
    owner: "root"
    group: "root"
    mode: 0644
    backup: true
  vars:
    conf: "{{ _default_validator_config|combine(validator_config) }}"
    env_conf: "{{ validator_env_vars }}"
  register: "validator_container_env"

- name: Set Prysm container volume list
  set_fact:
    prysm_volumes:
      - "{{ host_data_dir }}:{{ data_dir }}"

- name: Add host config path to volume list when set
  when: host_config is defined and host_config|length > 0
  set_fact:
    prysm_volumes:
      - "{{ host_data_dir }}:{{ data_dir }}"
      - "{{ host_config }}:{{ prysm_config_dir }}/config.yml"

- name: Start Prysm beacon-chain service
  when: '"beacon-node" in target_services'
  community.docker.docker_container:
    name: prysm-beacon
    image: "{{ image }}"
    command:
      - "beacon-chain"
      - "--config-file={{ prysm_config_dir }}/config.yml"
    env_file: "{{ beacon_env_file }}"
    published_ports:
      - "{{ p2p_tcp_port }}:13000/tcp"
      - "{{ p2p_udp_port }}:12000/udp"
      - "{{ eth2_api_port }}:3501/tcp"
      - "{{ beacon_rpc_port }}:4000/tcp"
      - "{{ beacon_metrics_port }}:8080/tcp"
    volumes: "{{ prysm_volumes }}"
    networks:
      - name: ethereum
    cpus: "{{ cpus }}"
    memory: "{{ memory }}"
    restart_policy: "{{ restart_policy }}"

- name: Start Prysm validator service
  when: '"validator" in target_services'
  community.docker.docker_container:
    name: prysm-validator
    image: "{{ image }}"
    command:
      - "validator"
      - "--config-file={{ prysm_config_dir }}/config.yml"
    env_file: "{{ validator_env_file }}"
    published_ports:
      - "{{ validator_gateway_port }}:7500/tcp"
      - "{{ validator_rpc_port }}:7000/tcp"
      - "{{ validator_metrics_port }}:8081/tcp"
    volumes:
      - "{{ host_data_dir }}:{{ data_dir }}"
      - "{{ host_wallet_dir }}:/wallets"
      - "{{ host_keys_dir }}:/keys"
    networks:
      - name: ethereum
    cpus: "{{ cpus }}"
    memory: "{{ memory }}"
    restart_policy: "{{ restart_policy }}"
