---
galaxy_info:
  author: O1 Labs
  role_name: prysm
  description: Prysm, a full-featured client for the Ethereum 2.0 protocol written in Go
  company: "O1.IO"
  license: MIT
  min_ansible_version: 2.5
  platforms:
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - cosmic
  galaxy_tags:
    - blockchain
    - ethereum
    - eth2
    - beacon-chain
    - validator
    - crypto
