---
system_dependencies:
  - build-essential
  - pkg-config
  - libc6-dev
  - m4
  - g++-multilib
  - autoconf
  - libtool
  - ncurses-dev
  - unzip
  - git
  - python
  - python-zmq
  - zlib1g-dev
  - curl
  - bsdmainutils
  - automake
