---
- name: Ensure existence of runtime dirs
  become: true
  file:
    path: "{{ dir }}"
    state: directory
    mode: 0777
  loop:
    - "{{ _ops_runtime_dir }}"
  loop_control:
    loop_var: dir

- name: Generate monitoring compose config
  become: true
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ _ops_runtime_dir }}/docker-compose.yml"
    owner: "root"
    group: "root"
    mode: 0644
    backup: true
  register: "monitoring_compose"

- name: Generate Prometheus config
  become: true
  when: '"prometheus" in target_services'
  template:
    src: "prometheus.yml.j2"
    dest: "{{ host_prometheus_config }}"
    owner: "root"
    group: "root"
    mode: 0644
    backup: true
  register: "prometheus_config"

- name: Generate Promtail config
  become: true
  when: '"promtail" in target_services'
  template:
    src: "promtail.yml.j2"
    dest: "{{ host_promtail_config }}"
    owner: "root"
    group: "root"
    mode: 0644
    backup: true
  register: "promtail_config"

- name: Deploy monitoring services compose
  community.docker.docker_compose:
    project_src: "{{ _ops_runtime_dir }}"
    state: "{{ target_state }}"
    services: "{{ target_services }}"
    env_file: "{{ _config_env_file }}"
