managed_node: 
  hosts: 
    rocky1:
  vars: 
    ansible_host: 192.168.122.79
    ansible_user: root 
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

localhost:
  hosts: 
    local:
  vars: 
    ansible_host: 127.0.0.1
    ansible_password: terminal
    ansible_user: thanhtut