download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/felixfontein-acme-0.8.1.tar.gz
format_version: 1.0.0
name: acme
namespace: felixfontein
server: https://galaxy.ansible.com/api/
signatures: []
version: 0.8.1
version_url: /api/v3/plugin/ansible/content/published/collections/index/felixfontein/acme/versions/0.8.1/
