---
driver:
  name: docker

# Special config for enabling systemd init
default_driver_config: &default_driver_config
  run_command: /sbin/init
  cap_add:
    - SYS_ADMIN
  run_options:
    env: container=docker
  volume:
    - /sys/fs/cgroup:/sys/fs/cgroup
  provision_command:
    - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
    - systemctl enable sshd.service

transport:
  # TODO: remove with better solution than workaround:
  # https://github.com/test-kitchen/test-kitchen/issues/1035
  max_ssh_sessions: 6

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_pip: true
  ansible_version: 2.9.4
  ansible_verbose: true
  ansible_cfg_path: test/ansible.cfg
  requirements_path: test/requirements-test.yml
  idempotency_test: true
  require_chef_for_busser: false
  require_ruby_for_busser: false

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
  - name: debian-9
    driver_config:
      <<: *default_driver_config
      run_command: /lib/systemd/systemd
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service

suites:
  - name: package_install
    provisioner:
      playbook: test/integration/install/package_install/default_playbook.yml
      ansible_extra_flags: '--skip-tags=config,launch'
    verifier:
      inspec_tests:
        - path: test/integration/install/package_install
  - name: daemon_config
    provisioner:
      playbook: test/integration/config/daemon_config/default_playbook.yml
      ansible_extra_flags: '--skip-tags=launch'
    verifier:
      inspec_tests:
        - path: test/integration/config/daemon_config
  - name: launch-daemon
    provisioner:
      playbook: test/integration/launch/daemon/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/launch/daemon
  - name: launch-snark-worker
    provisioner:
      playbook: test/integration/launch/snark-worker/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/launch/snark-worker
