---
setup_mode: compose
target_state: present

restart_policy: unless-stopped
_ops_runtime_dir: /var/tmp/monitoring
_config_env_file: "{{ _ops_runtime_dir }}/.env"

prometheus_image: bitnami/prometheus:2.29.1
promtail_image: grafana/promtail:2.3.0
prometheus_port: 9090

host_prometheus_config: "{{ _ops_runtime_dir }}/prometheus.yml" 
host_promtail_config: "{{ _ops_runtime_dir }}/promtail.yml"
prometheus_config_path: /etc/prometheus/prometheus.yml
prometheus_data_dir: /opt/bitnami/prometheus/data
prometheus_retention_time: 30d
prometheus_listen_addr: 0.0.0.0:9090
target_services: [ 'node-exporter' ]
monitored_services: []
prometheus_scrape_configs: []

grafana_image: grafana/grafana:8.1.2
grafana_port: 3000
grafana_config_path: /etc/grafana/grafana.ini
grafana_data_dir: /var/lib/grafana
grafana_plugins: "grafana-clock-panel,grafana-simple-json-datasource"

loki_image: grafana/loki:2.3.0
loki_config_path: /etc/loki/local-config.yaml
loki_port: 3100

node_exporter_image: quay.io/prometheus/node-exporter:v1.2.2
node_exporter_port: 9100
