---
- name: Create configuration directory
  become: true
  file:
    path: "{{ config_dir }}"
    state: directory
    owner: "{{ zecminer_user }}"
    group: "{{ zecminer_user }}"
  tags:
    - config

- name: Copy Zecminer configuration in place
  become: true
  template:
    src: "miner.cfg.j2"
    dest: "{{ config_dir }}/miner.cfg"
    owner: "{{ zecminer_user }}"
    group: "{{ zecminer_user }}"
    mode: 0644
  vars:
    config: "{{ zecminer_config }}"
  notify:
    - Restart service
  tags:
    - config
