---
- name: Ensure Zecminer group exists
  become: true
  group:
    name: "{{ zecminer_user }}"
    state: present
    system: true
  tags:
    - install

- name: Create Zecminer user
  become: true
  user:
    comment: Zecminer client account
    name: "{{ zecminer_user }}"
    group: "{{ zecminer_user }}"
    shell: "/sbin/nologin"
    system: true
    create_home: false
  tags:
    - install

- name: Create installation directory
  become: true
  when: install_type == "archive"
  file:
    path: "{{ install_dir }}"
    state: directory
    owner: "{{ zecminer_user }}"
    group: "{{ zecminer_user }}"
  tags:
    - install

- name: Extract Zecminer archive
  become: true
  when: install_type == "archive"
  unarchive:
    src: "{{ archive_url }}"
    dest: "{{ install_dir }}"
    owner: "{{ zecminer_user }}"
    group: "{{ zecminer_user }}"
    mode: '0775'
    remote_src: true
    extra_opts: "{{ archive_options }}"
  tags:
    - install
    - archive

- name: Create a symbolic link to installed binary
  become: true
  when: install_type == "archive"
  file:
    src: "{{ install_dir }}/miner"
    dest: "{{ _exe_dir }}/miner"
    owner: "{{ zecminer_user }}"
    group: "{{ zecminer_user }}"
    state: link
  tags:
    - install
    - archive
