---
- name: Include OS and distribution specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
      skip: true
  tags:
    - preflight

- name: Check for uninstall signal
  when: perform_uninstall
  block:
    - name: Broadcast uninstall signal
      command: /bin/true
      notify:
        - Uninstall service
  always:
    - name: Ensure flush of handlers
      meta: flush_handlers
    - name: End play following uninstallation
      meta: end_play
  tags:
    - preflight

- name: Update system dependencies
  become: true
  when: ansible_os_family|lower == "redhat"
  yum:
    name: "{{ system_dependencies }}"
    state: present
  tags:
    - preflight

- name: Ensure proper configuration directory default
  when: config_dir is not defined or config_dir|length == 0
  set_fact:
    config_dir: "{{ install_dir }}"

- name: Add Nvidia Graphics PPA
  become: true
  when: ansible_os_family|lower == "debian"
  apt_repository:
    repo: 'ppa:graphics-drivers/ppa'
    state: present
    update_cache: true
  tags:
    - install
    - package
    - debian

- name: Update graphics/cuda packages
  become: true
  package:
    name: "{{ graphics_packages }}"
    state: present
  tags:
    - preflight
