---
driver:
  name: docker

# Special config for enabling systemd init
default_driver_config: &default_driver_config
  run_command: /sbin/init
  cap_add:
    - SYS_ADMIN
  run_options:
    env: container=docker
  volume:
    - /sys/fs/cgroup:/sys/fs/cgroup
  provision_command:
    - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
    - systemctl enable sshd.service

transport:
  # TODO: remove with better solution than workaround:
  # https://github.com/test-kitchen/test-kitchen/issues/1035
  max_ssh_sessions: 6

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_pip: true
  ansible_version: 2.9.9
  ansible_verbose: true
  ansible_cfg_path: test/ansible.cfg
  requirements_path: test/requirements-test.yml
  idempotency_test: true
  require_chef_for_busser: false
  require_ruby_for_busser: false

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver_config:
      <<: *default_driver_config
    provisioner:
      ansible_cfg_path: test/ansible-legacy.cfg
  - name: fedora-32
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
        - yum -y install python-pip
  - name: fedora-33
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
        - yum -y install python-pip
  - name: ubuntu-18.04
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
  - name: ubuntu-20.04
    driver_config:
      <<: *default_driver_config
      provision_command:
        - apt-get -y update
        - apt-get install python-pip
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
  - name: debian-8
    driver_config:
      <<: *default_driver_config
      run_command: /lib/systemd/systemd
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
    provisioner:
      ansible_cfg_path: test/ansible-legacy.cfg
  - name: debian-9
    driver_config:
      <<: *default_driver_config
      run_command: /lib/systemd/systemd
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service

suites:
  - name: install_archive
    provisioner:
      playbook: test/integration/install/install_archive/default_playbook.yml
      ansible_extra_flags: '--skip-tags=config,launch'
      idempotency_skip_tags:
        - config
        - launch
    verifier:
      inspec_tests:
        - path: test/integration/install/install_archive
    excludes:
      - centos-7
      - debian-8
      - debian-9
  - name: install_source
    provisioner:
      playbook: test/integration/install/install_source/default_playbook.yml
      ansible_extra_flags: '--skip-tags=config,launch'
      idempotency_skip_tags:
        - config
        - launch
    verifier:
      inspec_tests:
        - path: test/integration/install/install_source
    excludes:
      - centos-7
      - debian-8
      - debian-9
  - name: config
    provisioner:
      playbook: test/integration/config/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/config
    excludes:
      - centos-7
      - debian-8
      - debian-9
  - name: launch_service
    provisioner:
      playbook: test/integration/launch/launch_service/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/launch/launch_service
    excludes:
      - centos-7
      - debian-8
      - debian-9
  - name: launch_miner
    provisioner:
      playbook: test/integration/launch/launch_miner/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/launch/launch_miner
    excludes:
      - centos-7
      - debian-8
      - debian-9
  - name: uninstall
    provisioner:
      playbook: test/integration/uninstall/default_playbook.yml
      idempotency_test: false
    verifier:
      inspec_tests:
        - path: test/integration/uninstall
    excludes:
      - centos-7
      - debian-8
      - debian-9
