---
galaxy_info:
  author: O1 Labs
  role_name: chainlink
  description: Chainlink, a smart-contract platform data oracle network
  company: "O1.IO"
  license: MIT
  min_ansible_version: 2.5
  platforms:
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - cosmic
  galaxy_tags:
    - blockchain
    - chainlink
    - oracle
    - smart-contract
    - ethereum
    - crypto
