---
zecminer_user: zecminer

system_dependencies: []
graphics_packages: []

install_type: archive
install_dir: /opt/zecminer

archive_url: https://github.com/nano-pool/ewbf-miner/releases/download/miner/Zec.miner.0.4pro.Linux.Bin.tar.gz
archive_options: []

config_dir: "{{ install_dir }}"
zecminer_config: {}

_exe_dir: /usr/bin
_service_name: zecminer
extra_run_args: []
custom_unit_properties: {}

perform_uninstall: false
